CC     = gcc
OPTS   = -Wall -fPIC
INCS   = 
LIBS   = -L. -lDisk

SRCS   = LibFS.c 
OBJS   = $(SRCS:.c=.o)
TARGET = libFS.so

all: $(TARGET)

clean:
	rm -f $(TARGET) $(OBJS)

%.o: %.c
	$(CC) $(INCS) $(OPTS) -c $< -o $@ -std=c99

$(TARGET): $(OBJS)
	$(CC) -shared -o $(TARGET) $(OBJS) $(LIBS) -std=c99
